name: Build "turnip"

on:
  workflow_dispatch:
  schedule:
  - cron: "20 5 1,15 * *"

jobs:
  start_building_turnip:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y
    
    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Upload meson and ninja logs for debugging
        path: |
          turnip_workdir/ninja_log
          turnip_workdir/mesa/build-android-aarch64/meson-logs/meson-log.txt
          turnip_workdir/turnip.zip
          
    - id: versions
      run: |
        {
          "description=$(cat turnip_workdir/description)"
          "name=$(cat turnip_workdir/release)"
          "tag=$(cat turnip_workdir/tag)"
        } >> $GITHUB_OUTPUT
      
    - name: Release "turnip"
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.versions.outputs.description }} 
        tag_name: ${{ steps.versions.outputs.tag }}
        name: ${{ steps.versions.outputs.name }}
        files: |
           turnip_workdir/turnip.zip
